version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Ho_Chi_Minh"
    versioning-strategy: increase
    allow:
      - dependency-type: "all"
    target-branch: "develop"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "dependabot"
    commit-message:
      - prefix: "npm"
      - prefix-development: "chore"
      - include: "scope"
    assignees:
      - harrytran998
    reviewers:
      - harrytran998
